### ISSUE TITLE
Is the JSON API going to be added?

### ISSUE THREAD

**Issue by Grimm2017** [fireice-uk/xmr-stak-amd#172] opened 2017-11-15 23:45 UTC
I see the CPU version has a JSON API.  Is that going to be added to the AMD version?

**Comment by aaronsace** [comment] 2017-11-16 00:01
They are being merged: 
https://github.com/fireice-uk/xmr-stak

**Comment by psychocrypt** [comment] 2017-11-19 20:25
We released a new version of the miner: https://github.com/fireice-uk/xmr-stak
Please check if the issue still exists with the new version. 
If the problem is not fixed so far please open a new issue in [the issue section of the new reposetory](https://github.com/fireice-uk/xmr-stak/issues)

**Closed by psychocrypt** 2017-11-19 20:25 UTC
